---
# This playbook contains plays to deploy a strimzi (kafka) cluster
# in an isolated namespace

- set_fact:
    install_url: "https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.11.1/strimzi-cluster-operator-0.11.1.yaml"

- block:
    - name: Create a '{{ kafka_namespace }}' namespace
      command: kubectl create ns {{ kafka_namespace }}

    - name: Download strimzi installation files
      shell: "curl -s -L {{ install_url }} \\ 
      | sed 's/namespace: .*/namespace: {{ kafka_namespace }}/' \\
      | kubectl -n {{ kafka_namespace }} apply -f -"
      register: result
      failed_when: result.stderr != "" and "already exists" not in result.stderr

    # Create the persistent template with 3 Kafka replicas 
    # and 3 zookeeper replicas
    - template:
        src: persistent-template.yml.j2
        dest: /tmp/persistent-template.yaml

    - name: Provision a simple cluster
      command: kubectl apply -f /tmp/persistent-template.yaml -n {{ kafka_namespace }}

    # Delete the temp file
    - file: path=/tmp/persistent-template.yaml state=absent

  # Clean up if the tasks fail
  rescue:
    - debug:
        msg: "Kafka playbook failed. Cleaning up..."

    - name: Deleting {{ kafka_namespace }} namespace
      command: kubectl delete ns {{ kafka_namespace }}
